### ISSUE TITLE
Dwarf therapist not compiling with USE=qt4

### ISSUE THREAD

**Issue by fchaix** [anders-larsson/gentoo-overlay#12]
On my system, I wasn't able to compile dwarf-therapist without disabling the qt4 USE and enabling qt5.

My build.log (with USE="qt4") : http://sprunge.us/ORWj

**Comment by anders-larsson** [comment]
Thank you for finding this. It does not seem to build for me either with qt4 USE flag. I'm certain that I tested it just when 31.0.0 was released.
I'll look into it.

**Comment by anders-larsson** [comment]
It seems like qmake4 does something magical to the .pro file which messes up the build. Compare eqmake4 and eqmake5 functions here https://github.com/gentoo/qt/blame/master/eclass/qmake-utils.eclass. Seems like dwarf-therapist build breaks if it isn't built as a Release+Debug build.

I tried to build it manually from the directory portage used as its temporary directory and found that it had modified the .pro to the following: https://bpaste.net/show/5d09a47f52d8. Building manually with these modifications fails. It builds cleanly after these changes are reseted though..

Not sure how to work around it to be honest. I'll ask around!

**Comment by anders-larsson** [comment]
I've created this issue https://github.com/splintermind/Dwarf-Therapist/issues/245 upstream. It seems like Dwarf-therapist only can be built when CONFIG=debug_and_release is passed. Hopefully it can be fixed. I'll see if it can find a way to fix it temporarily with sed.

**Comment by anders-larsson** [comment]
Hello again,

I've worked around this issue by using sed to make it compile as a "debug_and_release" build again which solves the issue.
https://github.com/anders-larsson/gentoo-overlay/commit/f2f2c3f363772ec12c7669759f7bae6645f9d5d8

Feel free to verify that it works correctly for you and thank you for finding it!
