### ISSUE TITLE
discord not available from gentoo mirrors

### ISSUE THREAD

**Issue by saintdev** [anders-larsson/gentoo-overlay#16]
It might be a good idea to add `RESTRICT=mirror` to the ebuild.

**Comment by anders-larsson** [comment]
cool. Haven't had any issues because of it. I guess it fails back to upstream if the file is not found on gentoo's mirrors? Will look into it once I'm home from work. Feel free to create a pull request though.

**Comment by anders-larsson** [comment]
Solved in https://github.com/anders-larsson/gentoo-overlay/commit/bcbce0f2df18ee86de7170dd75b22c17ed1a9b8c.

**Comment by saintdev** [comment]
Thanks!
