### ISSUE TITLE
Overlay "anders-larsson" does not exist.

### ISSUE THREAD

**Issue by Haikson** [anders-larsson/gentoo-overlay#17]
# layman -a anders-larsson

 * Adding overlay,...
 * Exception: Overlay "anders-larsson" does not exist.

 * CLI: Errors occurred processing action add
 * Exception: Overlay "anders-larsson" does not exist.

**Comment by anders-larsson** [comment]
Hello,

Looking in https://api.gentoo.org/overlays/repositories.xml it should exist in Gentoo's official layman repository list. Have you updated your local layman repository list using `layman -f`?

**Comment by Haikson** [comment]
Thanks. It's works )

**Comment by anders-larsson** [comment]
cool. Glad it helped and I hope the ebuilds will make it easier for you. If you have any suggestions on improvements for the ebuilds don't hesitate to create pull requests/issues.
