### ISSUE TITLE
Discord Canary 0.0.10 Version Bump

### ISSUE THREAD

**Issue by gitgud-software** [anders-larsson/gentoo-overlay#23]
Been using this for a overlay bit now, and just wanted to thank you for maintaining it. I just got the notification for the new version bump starting up the client. Hope to see a new ebuild soon!

**Comment by anders-larsson** [comment]
Ask and you shall receive! I've updated the overlay with an ebuild for 0.0.10.
Enjoy!

**Comment by gitgud-software** [comment]
![screenshot from 2016-11-04 23-39-38](https://cloud.githubusercontent.com/assets/10673048/20027348/17e5fb98-a2e8-11e6-8196-6ee324a6e6c5.png)

Looks like something's up.

**Comment by gitgud-software** [comment]
Works just fine, I got a Javascript error spat at me the first time I tried to launch it but restarting the PC fixed the issue. Cheers!
